### ISSUE TITLE
ImageMagick install error on Linux Mint 19.1

### ISSUE THREAD

**Issue by kdechant** [jeebak/devtools#2]
I saw this error when running slipstream on a fresh install of Mint 19.1: https://github.com/Homebrew/homebrew-core/issues/36000 (C compiler error when installing imagemagick via Linuxbrew).

I ran `brew link --overwrite libomp` then ran slipstream again and it seemed to fix it.

**Comment by jeebak** [comment]
Weird. I didn't get a notification email for this. Yeah, linuxbrew's a bit of a moving target right now. When packages are updated, there's a lag before bottles (pre-compiled binaries) are generated (some a few hours, some days, some weeks.)

**Comment by jeebak** [comment]
Phew. Linuxbrew's been merged into Homebrew. Hopefully things like this won't happen again, presumably w/ bottles being available for Linux w/ each release.
```
 brew upgrade
==> Migrating from Linuxbrew/brew to Homebrew/brew
  Linuxbrew/brew has been merged into Homebrew/brew!
  Linuxbrew/brew will no longer be updated.
  Your git remote has been changed from
     https://github.com/Linuxbrew/brew
  to https://github.com/Homebrew/brew
  See the blog post at https://brew.sh/2019/02/02/homebrew-2.0.0/
```
