### ISSUE TITLE
OSX Mojave problems with Slipstream

### ISSUE THREAD

**Issue by AaronAmstutz** [jeebak/devtools#3]
Having some sort of weirdness with Mojave and Slipstream. Mostly just with getting apache/php-fpm/etc to a workable state. I've been trying to debug for a couple days on and off, but haven't been able to figure out the cause.

Here's what I have:
OSX version -
![screen shot 2019-02-17 at 10 30 15 am](https://user-images.githubusercontent.com/1263675/52917339-0e24ea80-329f-11e9-89b0-4cc8b5b96e38.png)
When I run `brew services list`
![screen shot 2019-02-17 at 10 30 55 am](https://user-images.githubusercontent.com/1263675/52917347-25fc6e80-329f-11e9-938d-3e506f141ba4.png)

Oddly, mariadb says `error` but I can access it via Sequel Pro and command line. So I'm not worried about that at this point.
![screen shot 2019-02-17 at 10 32 25 am](https://user-images.githubusercontent.com/1263675/52917363-5c39ee00-329f-11e9-8986-0f6989462dce.png)

`httpd` and `dnsmasq` seem to be running (according to `brew services list`), and .localhost responds to a ping:
![screen shot 2019-02-17 at 10 34 13 am](https://user-images.githubusercontent.com/1263675/52917386-9c996c00-329f-11e9-8fa4-0f0b7fb4b7ca.png)
but gives a "connection refused" when I try to curl 
![screen shot 2019-02-17 at 10 35 57 am](https://user-images.githubusercontent.com/1263675/52917405-e08c7100-329f-11e9-8f5c-cfecc7b6a249.png)

I've been reading through slipstream.bash and trying to parse out which part maybe doesn't match my system, but I'm drawing a blank.

@jeebak any thoughts on where to look next? No apache logs are being created, and I don't see any errors if I restart the brew services.

**Comment by jeebak** [comment]
re: `httpd`, try running: `accomplice adb` (apache debug) to see if that sheds any light.

Also, look at:
* `/usr/local/etc/httpd/httpd.conf`
* `/usr/local/etc/extra/localhost.conf`
particularly the `Listen` directive:
```
grep -r Listen /usr/local/etc/httpd/{httpd.conf,extra/localhost.conf}
```
commenting/deleting out any dupes, restart the brew service.

**Comment by AaronAmstutz** [comment]
Ah! So that's interesting. It looks like apache's using that httpd.conf, not the one in /etc/apache2. Slipstream made changes to /etc/apache2/httpd.conf, but that's not the one being used?
![screen shot 2019-02-17 at 11 17 15 am](https://user-images.githubusercontent.com/1263675/52917949-c2297400-32a5-11e9-988a-8294997b5eca.png)

**Comment by AaronAmstutz** [comment]
Ah!x2, I see 
`# TODO: switch from using system apache to homebrew apache
# # Neuter System Apache, and don't worry about and /etc/ droppings
# if qt  pgrep    -f "/usr/sbin/httpd"; then
#   sudo pkill -9 -f "/usr/sbin/httpd"
#
#   show_status "Unloading: /System/Library/LaunchDaemons/org.apache.httpd.plist"
#   sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist
# fi`
in Slipstream

**Comment by jeebak** [comment]
Yeah. I merged in the changes to switch from apple apache to homebrew apache recently. Hmm... from the `adb` screenshot, it looks like the script didn't set: `ServerName 127.0.0.1` 

Also, of concern is the User and Group still being `_www`. Slipstream should have set it to your `$USER`. Try updating those manually, and restarting the brew service.

**Comment by AaronAmstutz** [comment]
Boom! Figured it out. Line 614 in slipstream.bash should be:
`APACHE_BASE="/usr/local/etc/httpd"` 
instead of 
`APACHE_BASE="/etc/apache2"` 
And now it edits all the right files and localhost works!

**Comment by AaronAmstutz** [comment]
Thanks for the help man!

**Comment by jeebak** [comment]
Nice! I've added the patch in eaf6776e5915d45d5b9d9b207b7288e1c686929e. You're welcome. Thanks for reporting, and finding that.
